name = "discord-oidc"
main = "src/workers.ts"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "KV", id = "f77ba573d3ee412b96bffcdbee52f3aa", preview_id = "9df5fbc62080486dab8b5535212968cc" }
]

[triggers]
crons = ["0 */1 * * *"]

[vars]
DISCORD_CLIENT_ID="1240329292228071424"
REDIRECT_URL="https://wakcareers.cloudflareaccess.com/cdn-cgi/access/callback"
SERVERS_ROLE_CLAIMS=[
  "1228219266692546663"
]
CACHE_ROLES=true
